app/models/book.py
"""
 Created by yan on 2018/8/30 17:00
"""
__author__ = 'yan'

# flask 的很多东西都是复用和封装，werzeug,只提供最核心的功能

# sqlalchemy
# flask_sqlalchemy
# wtforms
# flask_wtforms

from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import Column,Integer,String


db = SQLAlchemy()

class Book(db.Model):
    """
       一些属性定义重复性比较大，元类可以解决这个问题
    """
    __tablename__ = 'book'

    id = Column(Integer, primary_key=True, autoincrement=True)
    title = Column(String(50), nullable=False)  # nullable 不允许为空
    _author = Column('author', String(30), default='未名')
    binding = Column(String(20))
    publisher = Column(String(50))
    price = Column(String(20))
    pages = Column(Integer)
    pubdate = Column(String(20))
    isbn = Column(String(15), nullable=False, unique=True)  # unique，isbn必须唯一，不能重复
    summary = Column(String(1000))
    image = Column(String(50))

app/forms/book.py
"""
 Created by yan on 2018/8/30 15:41
 验证web的book的参数
 使用wtforms做验证器的思想需要学习下
"""

from wtforms import Form,StringField,IntegerField
from wtforms.validators import Length,NumberRange,DataRequired

__author__ = 'yan'

class SearchForm(Form):
    q = StringField(validators=[DataRequired(message='q长度不能为空'),Length(min=1,max=30,message='长度为1-30')])
    page = IntegerField(validators=[NumberRange(min=1,max=99)],default=1)

app/__init__.py
"""
 Created by yan on 2018/8/30 14:52
"""
from flask import Flask
from app.models.book import db

__author__ = 'yan'

def create_app():
    # alt+enter 快捷导入
    app = Flask(__name__)
    print('__name__',__name__)  # app
    # 导入配置文件的路径
    app.config.from_object('app.secure')
    app.config.from_object('app.setting')
    register_blueprint(app)

    db.init_app(app)
    # 一个经典问题：No application found. Either work inside a view function or push
    # 方法一
    db.create_all(app=app)
    # 方法二，RPG代入感，移情，认同感，学习看源代码去学习
    # with app.context:
    #     db.create_all()
    # 方法三,在定义的时候，就直接引入这个核心对象
    # db = SQLAlchemy(app)

    return app


def register_blueprint(app):
    from app.web.book import web
    # 注册蓝图
    app.register_blueprint(web)

app/web/__init__.py
"""
 Created by yan on 2018/8/30 14:53
 蓝图的相关初始化工作
"""

__author__ = 'yan'

from app.web.blueprint import web

# 必须首先导入执行以下，否则没有引入，会有循环导入
from app.web import book

app/web/auth.py
from . import web

__author__ = '七月'


@web.route('/register', methods=['GET', 'POST'])
def register():
    pass


@web.route('/login', methods=['GET', 'POST'])
def login():
    pass


@web.route('/reset/password', methods=['GET', 'POST'])
def forget_password_request():
    pass


@web.route('/reset/password/<token>', methods=['GET', 'POST'])
def forget_password(token):
    pass


@web.route('/change/password', methods=['GET', 'POST'])
def change_password():
    pass


@web.route('/logout')
def logout():
    pass

app/web/blueprint.py
"""
 Created by yan on 2018/8/30 15:25
"""
from flask import Blueprint

__author__ = 'yan'

# 蓝图的蓝本
web = Blueprint('web',__name__)

app/web/main.py
from . import web


__author__ = '七月'


@web.route('/')
def index():
    pass


@web.route('/personal')
def personal_center():
    pass

app/templates/base.html
<!DOCTYPE HTML>
<html>

{% block title %}
    <title>鱼书</title>
{% endblock %}

{% block head %}
    <link rel="stylesheet"
          href="{{ url_for('static', filename='3rd/ui/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}">
    <link rel="shortcut icon"
          href="{{ url_for('static', filename='images/icon.png') }}">
{% endblock %}

<body>
{% block navbar %}
    <div class="nav-self">
        <div style="padding-top: inherit" class="container">
            <form class="form-inline" action="{{ url_for('web.search') }}" method="get">
                <div class="flex-vertical-center-height">
                    <div class="col-md-2">
                        <img src="{{url_for('static', filename='images/logo-yushu.png')}}"/>
                    </div>
                    <div style="margin-left:30px;" class="col-md-8 input-group">
                        <input name="q" type="text" placeholder="ISBN、图书名称"
                               class="form-control input-sm">
                        <span class="input-group-btn">
                            <input class="btn btn-search" type="submit" value="搜索"/>
                        </span>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="sub-nav flex-vertical-center">
        <div class="container">
            <div class="row">
                <div class="col-md-2 col-md-offset-1">
                    <a id="recent" href="{{ url_for('web.index') }}"
                       class="flex-vertical-hor-center">
                        <img src="{{ url_for('static', filename='images/upload.png') }}"/>
                        <span>最近上传</span>
                    </a>
                </div>
                <div class="col-md-2">
                    <a id="gifts" href="{{ url_for('web.my_gifts') }}"
                       class="flex-vertical-hor-center">
                        <img src="{{ url_for('static', filename='images/gift.png') }}"/>
                        <span>赠送清单</span>
                    </a>
                </div>
                <div class="col-md-2">
                    <a id="wishes" href="{{ url_for('web.my_wish') }}"
                       class="flex-vertical-hor-center">
                        <img src="{{ url_for('static', filename='images/wish.png') }}"/>
                        <span>心愿清单</span>
                    </a>
                </div>
                <div class="col-md-2">
                    <a id="pending" href="{{ url_for('web.pending') }}"
                       class="flex-vertical-hor-center">
                        <img src="{{ url_for('static', filename='images/fish.png') }}"/>
                        <span>鱼漂</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="container-height flex-vertical-center float-menu">
        {% if not current_user.is_authenticated %}
            <div style="float:right">
                <a href="{{ url_for('web.login') }}">登录</a>
                <a style="margin-left: 40px;" href="{{ url_for('web.register') }}">注册</a>
            </div>
        {% else %}
            <a href="{{ url_for('web.personal_center') }}">{{ current_user.nickname }}的鱼书</a>
            <a style="margin-left: 40px;" href="{{ url_for('web.logout') }}">注销</a>
        {% endif %}
    </div>
{% endblock %}
<div class='container'>
    <div class="row">
        {% with messages = get_flashed_messages() %}
            {% for message in messages %}
                {% if message %}
                    <div class="alert alert-warning" role="alert">{{ message }}</div>
                {% endif %}
            {% endfor %}
        {% endwith %}
        {% if form and form.errors %}
            {% for key, error in form.errors.items() %}
                <div class="alert alert-warning" role="alert">{{ error }}</div>
            {% endfor %}
        {% endif %}
    </div>
    {% block content %} {% endblock %}
</div>
<div id="footer" class="flex-hor-center">
    <span>© 2017-2020 yushu.im created by 七月</span>
</div>
</body>

{% block scripts %}
    <script src="{{ url_for('static', filename='3rd/jquery-3.2.1.min.js') }}"></script>
    <script src="{{ url_for('static', filename='3rd/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/base.js') }}"></script>
    <script>
        $SCRIPT_ROOT = {{ request.script_root|tojson|safe }};
    </script>
{% endblock %}

</html>

app/templates/book_detail.html
{% extends "base.html" %}
{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='3rd/ui/remodal.css')}}">
    <link rel="stylesheet" href="{{ url_for('static', filename='3rd/ui/remodal-default-theme.css')}}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/book-detail.css')}}">
{% endblock %}
{% block content %}
    {{ super() }}
    <div class="row book-container">
        <div class="col-md-2">
            <img class="book-img" src="{{ book.image }}"/>
        </div>
        <div style="margin-left: 30px;" class="col-md-5 flex-vertical">
            <div>
                <h4>{{ book.title }}</h4>
            </div>
            <div class="description-font-margin">
                <div>
                    <span>作者:</span>
                    <span>{{ book.author }}</span>
                </div>
                <div>
                    <span>出版社:</span>
                    <span>{{ book.publisher }}</span>
                </div>
                <div>
                    <span>出版年：</span>
                    <span>{{ book.pubdate }}</span>
                </div>
                <div>
                    <span>页数：</span>
                    <span>{{ book.pages }}</span>
                </div>
                <div>
                    <span>定价：</span>
                    <span>{{ book.price }}</span>
                </div>
                <div>
                    <span>精装：</span>
                    <span>{{ book.binding }}</span>
                </div>
                <div>
                    <span>ISBN：</span>
                    <span id="isbn">{{ book.isbn }}</span>
                </div>
                {% if wishes.total or gifts.total %}
                    <div class="color-count">
                        <span>{{ wishes.total }}人想要 / </span>
                        <span>{{ gifts.total}}人可赠送</span>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
    <div style="margin-top:30px;" class="row">
        {% if not has_in_gifts and not has_in_wishes %}
            <div class="col-md-1">
                <a class="btn btn-outline"
                   href="#modal">
                    赠送此书
                </a>
            </div>
            <div style="margin-left:30px;" class="col-md-1">
                <a class="btn btn-outline"
                   href="{{ url_for('web.save_to_wish', isbn=book.isbn) }}">
                    加入到心愿清单
                </a>
            </div>
        {% elif has_in_wishes %}
            <div class="col-md-3">
                <span class="bg-info">已添加至心愿清单</span>
            </div>
        {% else %}
            <div class="col-md-3">
                <span class="bg-info">已添加至赠送清单</span>
            </div>
        {% endif %}
    </div>
    <div style="margin-top: 30px;" class="row">
        <div class="col-md-2"><span class="description-title">内容简介</span></div>
    </div>
    <div style="margin-top:15px;" class="row">
        <div class="col-md-11">
            <p class="description-font">{{ book.summary }}</p>
        </div>
    </div>
    {% if gifts.total!= 0 and not has_in_gifts %}
        <div style="margin-top:30px;" class="row">
            <div class="col-md-3"><span class="description-title">向他们请求此书</span></div>
        </div>
        <hr style="margin-top:5px;"/>
        {% for gift in gifts.trades %}
            <div style="margin-top:30px;" class="row">
                <div class="col-md-1">
                    {{ gift.user_name }}
                </div>
                <div class="col-md-2 description-font">
                    上传于{{ gift.time }}
                </div>
                <div class="col-md-2">
                    <a class="btn-normal"
                       href="{{ url_for('web.send_drift', gid=gift.id) }}">向他请求此书</a>
                </div>
            </div>
        {% endfor %}
    {% endif %}
    {% if wishes.total != 0 and has_in_gifts %}
        <div style="margin-top:30px;" class="row">
            <div class="col-md-3"><span class="description-title">向他们赠送此书</span></div>
        </div>
        <hr style="margin-top:5px;"/>
        {% for wish in wishes.trades %}
            <div style="margin-top:30px;" class="row">
                <div class="col-md-1">
                    {{ wish.user_name }}
                </div>
                <div class="col-md-2 description-font">
                    上传于{{ wish.time }}
                </div>
                <div class="col-md-2">
                    <a class="btn-normal"
                       href="{{ url_for('web.satisfy_wish', wid=wish.id, isbn=[book.isbn]) }}">向他赠送此书</a>
                </div>
            </div>
        {% endfor %}
    {% endif %}
    <div class="remodal" data-remodal-id="modal" role="dialog"
         aria-labelledby="modal1Title" aria-describedby="modal1Desc"
         data-remodal-options="closeOnOutsideClick: false">
        <button data-remodal-action="close" class="remodal-close"
                aria-label="Close"></button>
        <div>
            <h5 class="diag-title">
                您确定拥有《{{ book.title }}》这本书吗？</h5>
            <p id="modal1Desc" class="description-font">
                如果您不想赠送此书，或者没有这本书，请不要随意发布虚假信息。谢谢你的支持和理解。
            </p>
        </div>
        <br>
        <button data-remodal-action="confirm" class="remodal-confirm">确定赠送</button>
        <button data-remodal-action="cancel" class="remodal-cancel">不，算了</button>
    </div>
{% endblock %}
{% block scripts %}
    {{ super() }}
    <script src="{{ url_for('static', filename='3rd/remodal.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/book-detail.js') }}"></script>
{% endblock %}

app/templates/drift.html
{% extends "base.html" %}
{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/drift.css')}}">
{% endblock %}
{% block navbar %}
{% endblock %}
{% block content %}
    <div style="margin-top:100px;" class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="row">
                <div class="col-md-2">
                    <a id='nav_url' href="{{ url_for('web.index') }}">去首页</a>
                </div>
            </div>
            <div class="bg-container">
                <div class="row">
                    <div class="col-md-12 text-center bg-head">
                        <span class="drift-title">向<span
                                class="space">{{ gifter.nickname }}</span>请求这本书</span>
                    </div>
                </div>
                <div style="margin-top:15px;" class="row">
                    <div class="col-md-10 col-md-offset-1 flex-vertical gifter-container">
                        <span class="sub-title-color">以下是书籍拥有者信息，诚信度供你参考:</span>
                        <span style="margin-top:10px; margin-bottom:10px;">{{ gifter.nickname }}</span>
                        <div><span
                                class="description-font">鱼豆：</span><span>{{ gifter.beans }}</span>
                        </div>
                        <div><span
                                class="description-font">接受/送出书籍：</span><span>{{ gifter.send_receive }}</span>
                        </div>
                    </div>
                </div>
                <div style="margin-top:10px;" class="row">
                    <div class="col-md-10 col-md-offset-1">
                        <span class="main-color">本次交易将消耗你1个鱼豆，你当前还有{{ user_beans }}个鱼豆</span>
                    </div>
                </div>
                <form action="" method="post">
                    <div style="margin-top:20px;" class="row">
                        <div class="col-md-10 col-md-offset-1 flex-vertical input-margin">
                            <label class="sub-title-color" for="recipient_name">收件人姓名</label>
                            <div class="row">
                                <div class="col-md-5">
                                    <input placeholder="请填写收件人姓名" id="recipient_name"
                                           name="recipient_name"
                                           class="normal-input btn-block form-control"
                                           value="{{ form.recipient_name.data | default('', true) }}">
                                </div>
                            </div>
                            <label class="sub-title-color" for="mobile">联系电话</label>
                            <div class="row">
                                <div class="col-md-5">
                                    <input placeholder="如13818181818" id="mobile"
                                           name="mobile"
                                           class="normal-input btn-block form-control"
                                           value="{{ form.mobile.data | default('', true) }}">
                                </div>
                            </div>
                            <label class="sub-title-color" for="address">书籍收件地址</label>
                    <textarea class="form-control" rows="3" id="address" name="address"
                              placeholder="如，张三 北京市清华大学666室。请务必确保该地址能够收到书籍">{{ form.address.data | default('',true) }}</textarea>
                            <label class="sub-title-color" for="message">对他 / 她
                                说的话</label>
                        <textarea class="form-control" id="message" name="message"
                                  rows="4"
                                  placeholder="如有一些特别的要求，可以在这里填写">{{ form.message.data | default('',true) }}</textarea>
                        </div>
                    </div>
                    <div class="row">
                        <div style="position: relative;left:-20px;"
                             class="col-md-5 col-md-offset-4 flex-vertical text-center">
                            <input style="margin-top:12px;" type="submit"
                                   class="btn btn-big btn-block" value="提交">
                        <span style="margin-top:15px;"
                              class="main-color">提交信息，等待{{ gifter.nickname }}将书籍邮寄给你</span>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    <script src="{{ url_for('static', filename='3rd/jquery-3.2.1.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/drift.js') }}"></script>
{% endblock %}

app/templates/email_has_send.html
{% extends "base.html" %}
{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/index.css')}}">
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-md-12">
            <h6>一封邮件已发往你的注册邮箱，请及时查收</h6>
        </div>
    </div>
{% endblock %}

app/templates/gifts.html
{% extends "base.html" %}
{% block head %}
    {{ super() }}
   <link rel="stylesheet" href="{{ url_for('static', filename='css/gifts.css')}}">
{% endblock %}
{% block content %}
    <div class="row module-title shadow-bottom">
        <div class="col-md-2">
            <span class='description-title'>最近上传</span>
        </div>
        <hr/>
    </div>
    <div class="row">
        {% for book in recent.books %}
            <a href="{{ url_for('web.bool_detail', isbn=book.isbn) }}" class="">
                <div class="col-md-5 col-padding">
                    <div class="col-md-8">
                        <img class="book-img-base" src="{{ book.image }}">
                    </div>
                    <div class="col-md-9 flex-vertical">
                            <span id="title"
                                  style="font-size: 16px;margin-bottom: 15px">{{ book.title }}</span>
                        <span id="author">{{ book.author }}</span>
                        <span id="publisher">{{ book.publisher }}</span>
                        <span id="price">{{ book.price }}</span>
                    </div>
                </div>
            </a>
        {% endfor %}
    </div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% block head %}
    {{ super() }}
     <link rel="stylesheet" href="{{ url_for('static', filename='css/index.css')}}">
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-md-12">
        </div>
    </div>
    <div id="books" class="row">
        {% for book in recent %}
            <div class="col-md-4 book-container">
                <a href="{{ url_for('web.book_detail', isbn=book.isbn) }}" class="">
                    <div class="col-md-4 no-padding">
                        <img class="book-img cssshadow" src="{{ book.image }}">
                    </div>
                    <div style="margin-left: 0;" class="col-md-8 flex-vertical book-info">
                        <span class="title">{{ book.title }}</span>
                        <div class="description-font"><span>作者：</span><span>{{ book.author }}</span>
                        </div>
                        <span class="summary description-font">{{ book.summary }}</span>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
{% endblock %}

app/templates/my_gifts.html
{% extends "base.html" %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block content %}
    {{ super() }}
    <div class="row flex-vertical-center">
        <div style="margin-top:20px;" class="col-md-6">
            <span class="sub-title">我想赠送的书籍  共  {{ gifts | length }} 本</span>
            <hr>
        </div>
    </div>
    {% for gift in gifts %}
        <div class="row">
            <a href="{{ url_for('web.book_detail', isbn=gift.book.isbn) }}" class="">
                <div style="margin-bottom:30px;" class="col-md-9 col-padding">
                    <div class="col-md-2">
                        <img class="book-img-small shadow" src="{{ gift.book.image }}">
                    </div>
                    <div style="margin-top:6px;" class="col-md-6 flex-vertical">
                            <span id="title"
                                  class="book-middle-title">{{ gift.book.title }}</span>
                        <div style="margin-top:6px;"
                             class="flex-vertical description-font">
                            <span id="author">{{ gift.book.author }}</span>
                            <span id="publisher">{{ gift.book.publisher }}</span>
                            <span id="price">{{ gift.book.price }}</span>
                            <span id="isbn">{{ gift.book.isbn }}</span>
                        </div>
                        <a class="link-normal"
                           href="{{ url_for('web.redraw_from_gifts', gid=gift.id) }}">
                            撤销
                        </a>
                    </div>
                    <div class="col-md-3 flex-vertical">
                        {% if gift.wishes_count %}
                            <a href="{{ url_for('web.book_detail', isbn=gift.book.isbn) }}">
                                <span class="bg-info">{{ gift.wishes_count }}人想要</span>

                            </a>
                        {% endif %}
                    </div>
                </div>
            </a>
        </div>
    {% endfor %}
{% endblock %}
{% block scripts %}
    {{ super() }}
    <script src="{{ url_for('static', filename="js/util.js") }}"></script>
    <script src="{{ url_for('static', filename='js/search_result.js') }}"></script>
{% endblock %}

app/templates/my_wish.html
{% extends "base.html" %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block content %}
    {{ super() }}
    <div class="row flex-vertical-center">
        <div style="margin-top:20px;" class="col-md-6">
            <span class="sub-title">我想要的书籍  共  {{ wishes | length }} 本</span>
            <hr>
        </div>
    </div>
    {% for wish in wishes %}
        <div class="row">
            <a href="{{ url_for('web.book_detail', isbn=wish.book.isbn) }}" class="">
                <div style="margin-bottom:30px;" class="col-md-9 col-padding">
                    <div class="col-md-2">
                        <img class="book-img-small shadow" src="{{ wish.book.image }}">
                    </div>
                    <div style="margin-top:6px;" class="col-md-6 flex-vertical">
                            <span id="title"
                                  class="book-middle-title">{{ wish.book.title }}</span>
                        <div style="margin-top:6px;"
                             class="flex-vertical description-font">
                            <span id="author">{{ wish.book.author }}</span>
                            <span id="publisher">{{ wish.book.publisher }}</span>
                            <span id="price">{{ wish.book.price }}</span>
                            <span id="isbn">{{ wish.book.isbn }}</span>
                        </div>
                        <a class="link-normal"
                           href="{{ url_for('web.redraw_from_wish', isbn=wish.book.isbn) }}">
                            撤销
                        </a>
                    </div>
                    <div class="col-md-3 flex-vertical">
                        {% if wish.wishes_count %}
                            <a href="{{ url_for('web.book_detail', isbn=wish.book.isbn) }}">
                                <span class="bg-info">{{ wish.wishes_count }}人赠送</span>
                            </a>
                        {% endif %}
                    </div>
                </div>
            </a>
        </div>
    {% endfor %}

{% endblock %}
{% block scripts %}
    {{ super() }}
    <script src="{{ url_for('static', filename="js/util.js") }}"></script>
{% endblock %}

app/templates/not_enough_beans.html
{% extends "base.html" %}
{% block head %}
    {{ super() }}
 <link rel="stylesheet" href="{{ url_for('static', filename='css/not-enough.css')}}">
{% endblock %}
{#{% block navbar %}#}
{#    #}
{#{% endblock %}#}
{% block content %}
    <div style="margin-top:60px;" class="row">
        <div class="col-md-12 flex-vertical main-color">
            <span style="margin-bottom: 10px;" class="large-title">你没有足够的鱼豆或超过限制</span></span>
            <span>当前你有{{ beans }}个鱼豆</span>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-md-12">
            <span class="main-color">
                温馨提示：每请求1本书，需要消耗1个鱼豆；当你已经请求两本书时，你必须先赠送1本书籍。
            </span>
        </div>
    </div>
    <div class="row">
        <div style="margin-top:50px;margin-bottom:30px;" class="col-md-3">
            <span class="description-font">以下是获取鱼豆的方式</span>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2 bg">
            <span>1.  上传图书</span>
        </div>
        <div class="col-md-9 bg-opacity">
            <span>在搜索框内搜索书籍，并将书籍“加入到赠送清单” 即可获得0.5个鱼豆。务必确保你愿意赠送此书。</span>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2 bg">
            <span>2.  赠送图书</span>
        </div>
        <div class="col-md-9 bg-opacity">
            <span>每成功赠送一本图书，我们将额外赠送你1个鱼豆。</span>
        </div>
    </div>
{% endblock %}

app/templates/personal.html
{% extends "base.html" %}
{% block head %}
    {{ super() }}
     <link rel="stylesheet" href="{{ url_for('static', filename='css/personal.css')}}">
{% endblock %}
{% block navbar %}
{% endblock %}
{% block content %}
    <div class="row">
        <div style="margin-top:150px;" class="col-md-6 col-md-offset-3">
            <div class="row">
                <div class="col-md-2">
                    <a onclick="window.history.go(-1)" href="#">返回</a>
                </div>
            </div>
            <div class="bg-container">
                <div class="row">
                    <div class="col-md-4 col-md-offset-4 text-center">
                        <span class="big-title">{{ user.nickname }}</span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-8 col-md-offset-2 flex-vertical personal-detail">
                        <div><span>送出/收到：</span><span>{{ user.send_receive }}</span></div>
                        <div><span>当前鱼豆：</span><span>{{ user.beans }}</span></div>
                        <div><span>登录邮箱：</span><span>{{ user.email }}</span></div>
                        <div><span>登录密码：********* </span><a
                                href="{{ url_for('web.change_password') }}">修改</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/search_result.html
{% extends "base.html" %}
{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename = 'css/search-result.css')}}">
{% endblock %}
{% block content %}
    {{ super() }}
    <div style="margin-top:20px;" class="row flex-vertical-center">
        <div class="col-md-6">
            <span class="sub-title">搜索 <span class="space highlight"
                                             id="keyword">{{ books.keyword }}</span>的结果</span>
        </div>
        <div class="col-md-3 col-md-offset-3">
            <span class="sub-title"> 共 <span class="space"
                                             id="total">{{ books.total }}</span> 条记录</span>
        </div>
    </div>
    <hr>
    {% for book in books.books %}
        <div class="row col-padding">
            <a href="{{ url_for('web.book_detail', isbn=book.isbn) }}" class="">
                <div class="col-md-2">
                    <img class="book-img-small shadow" src="{{ book.image }}">
                </div>
                <div class="col-md-7 flex-vertical description-font">
                    <span class="title">{{ book.title }}</span>
{#                    <span>{{ [book.author | d(''), book.publisher | d('', true) , '￥' + book.price | d('')] | join(' / ') }}</span>#}
                    <span>{{book.intro}}</span>
                    <span class="summary">{{ book.summary | default('', true) }}</span>
                </div>
            </a>
        </div>
    {% endfor %}
    <div class="row">
        <div class="flex-hor-center">
            <ul class="pagination" id="pagination"></ul>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    {{ super() }}
    <script src="{{ url_for('static', filename='3rd/jquery.twbsPagination.min.js') }}"></script>
    <script src="{{ url_for('static', filename="js/util.js") }}"></script>
    <script src="{{ url_for('static', filename='js/search_result.js') }}"></script>
{% endblock %}